version: "3.3"

services:
  postgres:
    image: postgres:12.0
    restart: on-failure
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "vin-decoder"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nats:
    image: nats:2.6.6
    ports:
      - "8222:8222"
      - "4222:4222"
      - "6222:6222"
    volumes:
      - ./config/nats.conf:/config/nats.conf
      - nats-data:/data/nats-server
    command: "-c config/nats.conf"

volumes:
  postgres-data: {}
  nats-data: {}